[pytest]
# addopts defines default command-line arguments for every run
# -v: verbose output, -s: allow print statements, --html: generates a visual test report
addopts = -v -s --html=reports/report.html --self-contained-html

# Tells pytest which directory to search for tests to optimize discovery time
testpaths = tests

# Register custom markers to prevent Pytest Unknown Mark warnings
markers =
    smoke: critical test cases for quick system verification
    regression: comprehensive suite for full system validation


log_cli = true
log_cli_level = INFO