[pytest]
# addopts definiše standardne parametre za svako pokretanje
# --html=reports/report.html pravi vizuelni izveštaj
addopts = -v -s --html=reports/report.html --self-contained-html

# Govori pytest-u gde su testovi da ne gubi vreme na pretragu celog projekta
testpaths = tests

# Registrujemo markere da izbegnemo Warning poruke
markers =
    smoke: kritični testovi (brza provera)
    regression: kompletna provera sistema
